#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;
use MyConsoleApp\Command\CsvReaderCommand;

require __DIR__ . '/vendor/autoload.php';

$application = new Application();
$application->add(new CsvReaderCommand());
$application->run();
