#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Component\Console\Application;
use App\Command\CsvReaderCommand;

require __DIR__ . '/vendor/autoload.php';

$application = new Application();
$application->add(new CsvReaderCommand());
$application->run();
